### ISSUE TITLE
Update Brain Board Info

### ISSUE THREAD

**Issue by trickeydan** [srobo/docs#334]
- [x] https://github.com/srobo/docs/issues/340 
- [x] Update kit assembly instructions (#369)
- [x] #380
- [x] Update Updates Page (#337)
- [x] Update Brain Board Page (#355)
- [x] Add LED explanations (#355)
- [x] ~#338~
- [x] Remove all references to ODROID (#355)
- [ ] Update Power board docs to say That L2 is for powering the brain. (#375
